channels:
- conda-forge
dependencies:
- python=3.11.7
- pip<=25.2
- pip:
  - mlflow==3.5.0
  - cloudpickle==2.2.1
  - lz4==4.3.2
  - numpy==1.26.4
  - pandas==2.2.3
  - pathlib==1.0.1
  - psutil==5.9.0
  - scikit-learn==1.7.0
  - scipy==1.11.4
name: mlflow-env
