artifact_uri: file:///C:/Users/aly98/Desktop/Mlops/mlops_mlflow/127.0.0.1/0/7535bc5abaf7493da40e6a65a00458bc/artifacts
end_time: 1760683537043
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 7535bc5abaf7493da40e6a65a00458bc
run_name: fearless-goose-369
source_name: ''
source_type: 4
source_version: ''
start_time: 1760683536762
status: 3
tags: []
user_id: aly98
